services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: terms_of_use
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql
    networks:
      - terms-of-use-network

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DATA_DIR=/var/lib/localstack/data
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
    ports:
      - "4566:4566"
    volumes:
      - './localstack/setup-aws.sh:/etc/localstack/init/ready.d/setup-aws.sh' # ready hook
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - terms-of-use-network
  
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - terms-of-use-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./dockerfiles/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "13133:13133" # health_check extension
    networks:
      - terms-of-use-network

networks:
  terms-of-use-network:
    driver: bridge