services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: terms_of_use
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql
    networks:
      - terms-of-use-network

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,dynamodb,sns
      - DATA_DIR=/var/lib/localstack/data
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
      - AWS_ACCOUNT_ID=000000000000
    ports:
      - "4566:4566"
    volumes:
      - './localstack/setup-aws.sh:/etc/localstack/init/ready.d/setup-aws.sh' # ready hook
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - terms-of-use-network
  
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - terms-of-use-network

  valkey:
    image: bitnami/valkey:latest
    environment:
      - VALKEY_PASSWORD=fake
    ports:
      - "6379:6379"
    networks:
      - terms-of-use-network

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - terms-of-use-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./dockerfiles/grafana/grafana/provisioning:/etc/grafana/provisioning
      - ./dockerfiles/grafana/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - terms-of-use-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./dockerfiles/grafana/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - terms-of-use-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"  # Tempo HTTP API
    command:
      - -config.file=/etc/tempo/tempo.yaml
    volumes:
      - ./dockerfiles/grafana/tempo.yaml:/etc/tempo/tempo.yaml:ro
    networks:
      - terms-of-use-network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/config.yaml
    volumes:
      - ./dockerfiles/grafana/loki-config.yaml:/etc/loki/config.yaml
    networks:
      - terms-of-use-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "13133:13133" # health_check
      - "9464:9464"   # Prometheus exporter
    command:
      - --config=/etc/otel-collector-config.yaml
    volumes:
      - ./dockerfiles/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    networks:
      - terms-of-use-network
    depends_on:
      - tempo
      - loki
      - prometheus


networks:
  terms-of-use-network:
    driver: bridge
