name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  domain:
    name: Check domain package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/rust-setup
        with:
          package: domain
          all_features: true
      - name: Run domain tests
        run: cargo test -p domain --all-features

  inbound-features:
    needs: domain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up protoc
        uses: arduino/setup-protoc@v3
      - name: Setup
        uses: ./.github/actions/rust-setup
        with:
          package: inbound
          all_features: true
      - name: Run outbound tests for feature
        run: cargo test -p inbound --all-features

  outbound-features:
    needs: domain
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
        env:
          SERVICES: s3,sns,dynamodb
          EDGE_PORT: 4566
          AWS_DEFAULT_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: fake
          AWS_ACCESS_KEY_ID: fake
          AWS_ACCOUNT_ID: "000000000000"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/rust-setup
        with:
          package: outbound
          all-features: true

      - name: Wait for LocalStack on 4566
        run: |
          for i in $(seq 1 60); do
            if bash -c "</dev/tcp/localhost/4566" >/dev/null 2>&1; then
              echo "LocalStack is available"
              break
            fi
            echo "Waiting for LocalStack... ($i)"
            sleep 1
          done

      - name: Run outbound AWS tests
        env:
          AWS_ENDPOINT_URL: http://localhost:4566
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: 000000000000
          S3_BUCKET_NAME: test-bucket
          SNS_TOPIC_NAME: test-topic
        run: cargo test -p outbound --all-features

  terms-tests:
    needs:
      - outbound-features
      - inbound-features
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: ["aws,valkey,grpc", "gcloud,redis,actix-web,kafka,postgres"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up protoc
        if: contains(matrix.feature, 'grpc')
        uses: arduino/setup-protoc@v3

      - name: Setup
        uses: ./.github/actions/rust-setup
        with:
          package: terms-of-use
          features: "${{ matrix.feature }}"
